# Generated by Django 3.0.6 on 2020-05-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
    ]
